# Generated by Django 3.0 on 2025-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250925_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
