# Generated by Django 3.0 on 2025-11-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20251119_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='date',
            field=models.DateField(),
        ),
    ]
