# Generated by Django 3.0 on 2025-11-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20251119_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='stegimg',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
