# Generated by Django 3.0 on 2025-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
