# Generated by Django 5.2.9 on 2025-12-09 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_forward_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forward',
            name='USERS',
        ),
        migrations.AddField(
            model_name='forward',
            name='FUSERS',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forward',
            name='TUSERS',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
