# Generated by Django 5.2.9 on 2025-12-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ip', models.CharField(max_length=500)),
                ('user_agent', models.CharField(max_length=500)),
            ],
        ),
    ]
