# Generated by Django 5.2.9 on 2026-02-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_decoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=5000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
