# Generated by Django 5.2.9 on 2026-03-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_threat_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
