# Generated by Django 5.2.9 on 2026-04-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_users_aadhar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='FROMID',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='TOID',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='USERS',
        ),
        migrations.DeleteModel(
            name='Decoy',
        ),
        migrations.RemoveField(
            model_name='forward',
            name='FUSERS',
        ),
        migrations.RemoveField(
            model_name='forward',
            name='TUSERS',
        ),
        migrations.RemoveField(
            model_name='log',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='threat_notification',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='USERS',
        ),
        migrations.RemoveField(
            model_name='users',
            name='USER',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Forward',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Threat_notification',
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
